version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - "3307:3306"